# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default_twitter: &defaul_twitter
  twitter_api_key: p1OzZ90qlFtyEPNZRBn9WgiuD
  twitter_api_secret: QhIxRya41gjOKXSvveDgnzYk9kYQjBwtowR6GKNuq3dlb1DKXK


development:
  secret_key_base: 5bb893ba2cb9e41368adfb05cb0519c07ee36a93ba4cfd984a9c062490bc71825425c44d1bb7e59ff8240153db79135cccc37313758b2e1c17e63a4abf2c3503
  <<: *defaul_twitter

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  twitter_api_key: <%= ENV["TWITTER_KEY_BASE"] %>
  twitter_api_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
